services:

  db:
    container_name: postgres
    image: postgres
    env_file: .env.local
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-lms}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-lms}
      POSTGRES_DB: ${POSTGRES_DB:-lms}
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - lms
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file: .env.local
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - lms
    restart: unless-stopped

volumes:
  db:
  pgadmin:

networks:
  lms: